package com.autodocer.DTO;

/**
 * A simple record to hold the summary and description text
 * generated by the AiDescriptionService.
 *
 * @param summary A concise, one-sentence summary of the endpoint.
 * @param description A brief, human-readable description of what the endpoint does.
 */
public record AiGenerationResult(
        String summary,
        String description
) {}

