package com.autodocer.DTO;

/**
 * A simple record to hold the summary and description text
 * generated by the AiDescriptionService.
 */
public record AiGenerationResult(
        String summary,
        String description
) {}

